### ISSUE TITLE
Cache All Option?

### ISSUE THREAD

**Issue by voidale** [walmartlabs/react-ssr-optimization#12]
If you have plenty of components it's hard to keep track of everything, and It seems to me that you can actually cache everything with a template type of cache and it should work or I'm missing something?

Thanks

**Comment by mnaga** [comment]
@voidale,
Potentially yes, if the components are all pure view *without any* logic in them. For example, lets say you have a component where you use different css class based on the value of a prop (lets call it score). Then the score has to be part of the cacheKey for the template. So that you cache different templates based on the score.
On the other hand if you map score to a cssClass in redux or elsewhere and are simply passing that to the component then yes you are right. But what we have seen is there is always going to be some sort of 'view' logic based on property values hence the need for explicit declaration for which attributes are part of key and which ones are part of template. 
Regarding keeping track of everything, one idea we have been pondering was should we make the 'key' and template attributes as members of the component itself so that you don't have to manage them independently but we haven't had a need yet.
